namespace Zonit.Extensions.Tenants;

/// <summary>
/// Provides strongly-typed access to all tenant settings.
/// Properties are auto-generated based on classes inheriting from Setting&lt;T&gt;.
/// </summary>
/// <remarks>
/// Initializes a new instance of the <see cref="TenantSettings"/> class.
/// </remarks>
/// <param name="provider">The tenant provider.</param>
public partial class TenantSettings(ITenantProvider provider)
{
    // Properties will be auto-generated by TenantSettingsGenerator
    // Do not add properties manually - they will be generated automatically
    // based on classes that inherit from Setting<T>
}
