// <auto-generated/>
#if NETSTANDARD2_0
namespace System.Runtime.CompilerServices
{
    using System.ComponentModel;

    /// <summary>
    /// Reserved for use by a compiler for tracking metadata.
    /// This class allows the use of C# 9 init-only setters in projects targeting .NET Standard 2.0.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class IsExternalInit
    {
    }
}
#endif
